# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-17 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='day_url_pv_traffic',
            fields=[
                ('day', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=500)),
                ('traffic_sums', models.IntegerField(default=10)),
                ('page_view', models.IntegerField(default=10)),
                ('avg', models.FloatField(default=10)),
            ],
        ),
    ]
