# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-17 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstatistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day_url_pv_traffic',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
