# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-17 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webstatistics', '0002_auto_20171017_1354'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='day_url_pv_traffic',
            new_name='url_pv_traffic',
        ),
    ]
