# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-17 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webstatistics', '0003_auto_20171017_1355'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='url_pv_traffic',
            new_name='day_url_pv_traffic',
        ),
    ]
